'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (languageCode: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data for different languages
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.products': 'Products',
    'nav.support': 'Support',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.close': 'Close',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.manage': 'Manage your account and preferences',
    'profile.createAccount': 'Create Account',
    'profile.signIn': 'Sign In',
    'profile.editProfile': 'Edit Profile',
    'profile.logout': 'Logout',
    'profile.contactInfo': 'Contact Information',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.address': 'Address',
    'profile.password': 'Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.memberSince': 'Member since',
    'profile.orders': 'Orders',
    'profile.totalSpent': 'Total Spent',
    'profile.welcome': 'Welcome to Ryft',
    'profile.welcomeSubtitle': 'Create your account or sign in to get started',
    'profile.welcomeBack': 'Welcome back! Please sign in to your account.',
    'profile.joinRyft': 'Join Ryft and start your electric journey!',
    'profile.noOrders': 'No Orders Yet',
    'profile.noOrdersSubtitle': 'Start shopping to see your order history here.',
    'profile.startShopping': 'Start Shopping',
    'profile.wishlistEmpty': 'Your Wishlist is Empty',
    'profile.wishlistSubtitle': 'Start adding products to your wishlist to save them for later.',
    'profile.settingsComingSoon': 'Settings Coming Soon',
    'profile.settingsSubtitle': 'Account preferences and settings will be available here.',
    'profile.securityComingSoon': 'Security Features Coming Soon',
    'profile.securitySubtitle': 'Password management and security settings will be available here.',
    'profile.saveChanges': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.backToOptions': 'Back to options',
    'profile.enterFullName': 'Enter your full name',
    'profile.enterEmail': 'Enter your email',
    'profile.enterPhone': 'Enter your phone number',
    'profile.enterAddress': 'Enter your address',
    'profile.createPassword': 'Create a password',
    'profile.newPassword': 'Enter new password (leave blank to keep current)',
    'profile.confirmNewPassword': 'Confirm new password',
    'profile.notSet': 'Not set',
    'profile.maskedPassword': '••••••••',
    
    // Languages
    'languages.title': 'Choose Your Language',
    'languages.subtitle': 'Select your preferred language to view the Ryft website',
    'languages.apply': 'Apply Language',
    'languages.changed': 'Language changed successfully!',
    'languages.reloading': 'Reloading page with new language...',
    
    // Home Page
    'home.moveDifferent': 'Move Different. Ride the Shift.',
    'home.explore': 'Explore',
    'home.performanceLeads': 'Performance That Leads',
    'home.range75': '75 Mile Range',
    'home.rangeSubtitle': 'Go further with our next-gen battery tech.',
    'home.torque80': '80Nm Torque',
    'home.torqueSubtitle': 'Instant power delivery with smooth control.',
    'home.appControl': 'App Control',
    'home.appSubtitle': 'Track rides, lock remotely, monitor performance.',
    'home.gallery': 'Gallery',
    'home.ourMission': 'Our Mission',
    'home.pioneeringFuture': 'Pioneering the Future',
    'home.missionText': 'Ryft is pioneering the future of electric performance. Our mission is to deliver zero-compromise power, precision, and purity — allowing every rider to defy terrain, redefine adventure, and embrace electric dominance.',
    'home.power': 'Power',
    'home.powerSubtitle': 'Uncompromising electric performance that exceeds traditional combustion',
    'home.precision': 'Precision',
    'home.precisionSubtitle': 'Engineered for perfect control and handling in any condition',
    'home.purity': 'Purity',
    'home.puritySubtitle': 'Clean, sustainable technology that respects our planet',
    'home.whyRyft': 'Why \'Ryft\'?',
    'home.moreThanName': 'More Than a Name',
    'home.philosophy': 'The Philosophy',
    'home.theRift': 'The Rift',
    'home.riftText': 'The "rift" between gasoline past and electrified future. Where brute strength meets intelligence. Where silence speaks power.',
    'home.theRevolution': 'The Revolution',
    'home.revolutionText': 'We\'re not just building electric bikes — we\'re creating a revolution in how people think about performance, sustainability, and the future of transportation.',
    'home.theMeaning': 'The Meaning',
    'home.revolutionary': 'R - Revolutionary',
    'home.revolutionaryText': 'Breaking free from traditional constraints and limitations of combustion technology.',
    'home.youthful': 'Y - Youthful',
    'home.youthfulText': 'Embracing innovation and looking forward to the future with optimism and energy.',
    'home.freedom': 'F - Freedom',
    'home.freedomText': 'The freedom to ride anywhere, anytime, without environmental guilt or mechanical worry.',
    'home.technology': 'T - Technology',
    'home.technologyText': 'Cutting-edge electric technology that pushes the boundaries of what\'s possible.',
    'home.whereSilence': 'Where silence speaks power.',
    'home.ryftPhilosophy': '— The Ryft Philosophy',
    'home.whatIsRyft': 'What is Ryft?',
    'home.whatIsRyftText': 'Ryft isn\'t just an e-bike. It\'s a movement. Designed with precision, built with soul, and ready to redefine electric riding for a new generation.',
    'home.learnMore': 'Learn More',
    'home.readyToRide': 'Ready to Ride?',
    'home.readyToRideText': 'Preorder the Ryft One and join the electric movement.',
    'home.preorderNow': 'Preorder Now',
    
    // About Page
    'about.title': 'About Ryft',
    'about.subtitle': 'We\'re revolutionizing electric transportation by creating cutting-edge electric vehicles that combine innovative technology, sustainable design, and exceptional performance.',
    'about.ourMission': 'Our Mission',
    'about.missionText': 'To accelerate the world\'s transition to sustainable transportation by making electric vehicles that are not only environmentally friendly but also exciting to drive, beautiful to look at, and accessible to everyone. We believe that the future of mobility should be clean, efficient, and inspiring.',
    'about.ourValues': 'Our Values',
    'about.innovation': 'Innovation',
    'about.innovationText': 'Pushing the boundaries of electric transportation technology',
    'about.sustainability': 'Sustainability',
    'about.sustainabilityText': 'Committed to reducing carbon footprint and protecting our planet',
    'about.quality': 'Quality',
    'about.qualityText': 'Delivering exceptional products that exceed customer expectations',
    'about.community': 'Community',
    'about.communityText': 'Building a global community of electric vehicle enthusiasts',
    'about.ourStory': 'Our Story',
    'about.storyText1': 'Founded in 2025, Ryft began as a bold vision shared by two ambitious sophomores in high school who dreamed of revolutionizing electric transportation.',
    'about.storyText2': 'We started in our bedrooms and garages, learning everything we could about electric vehicles, battery technology, and sustainable design. What began as a school project has evolved into a real company with a mission to make electric transportation accessible to everyone.',
    'about.storyText3': 'Despite being young entrepreneurs, we\'re determined to prove that age is just a number when it comes to innovation. We\'re building the future of mobility while still attending high school, showing that great ideas can come from anywhere and anyone.',
    'about.fromHighSchool': 'From High School to Innovation',
    'about.fromHighSchoolText': 'Our journey from students to entrepreneurs',
    'about.meetOurTeam': 'Meet Our Team',
    'about.ceo': 'CEO',
    'about.cmo': 'CMO',
    'about.ceoBio': 'Leading Ryft with a vision to revolutionize electric transportation and make sustainable mobility accessible to everyone.',
    'about.cmoBio': 'Driving Ryft\'s marketing strategy and brand development to connect with electric vehicle enthusiasts worldwide.',
    'about.byTheNumbers': 'By The Numbers',
    'about.vehiclesDelivered': 'Vehicles Delivered',
    'about.countriesServed': 'Countries Served',
    'about.teamMembers': 'Team Members',
    'about.customerSatisfaction': 'Customer Satisfaction',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team. We\'re here to help you experience the future of electric transportation.',
    'contact.howCanWeHelp': 'How Can We Help?',
    'contact.callUs': 'Call Us',
    'contact.callSubtitle': 'Speak directly with our team',
    'contact.emailUs': 'Email Us',
    'contact.emailSubtitle': 'Send us a detailed message',
    'contact.liveChat': 'Live Chat',
    'contact.chatSubtitle': 'Get instant help online',
    'contact.sendMessage': 'Send Us a Message',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.selectSubject': 'Select a subject',
    'contact.generalInquiry': 'General Inquiry',
    'contact.salesQuestion': 'Sales Question',
    'contact.technicalSupport': 'Technical Support',
    'contact.testRideRequest': 'Test Ride Request',
    'contact.warrantyClaim': 'Warranty Claim',
    'contact.partsService': 'Parts & Service',
    'contact.yourFullName': 'Your full name',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.phonePlaceholder': '+1 (555) 123-4567',
    'contact.tellUsHow': 'Tell us how we can help you...',
    'contact.sendMessageButton': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.thankYou': 'Thank you! Your message has been sent successfully.',
    'contact.somethingWentWrong': 'Something went wrong. Please try again.',
    
    // Cart Page
    'cart.title': 'Your Cart',
    'cart.subtitle': 'item in your cart',
    'cart.subtitlePlural': 'items in your cart',
    'cart.emptyTitle': 'Your cart is empty',
    'cart.emptySubtitle': 'Ready to experience the future of electric riding?',
    'cart.continueShopping': 'Continue Shopping',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.free': 'Free',
    'cart.warranty': '3-Year Comprehensive Warranty',
    'cart.freeShipping': 'Free Shipping & Assembly',
    'cart.securePayment': 'Secure Payment Processing',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.whyChooseRyft': 'Why Choose Ryft?',
    'cart.revolutionaryPerformance': 'Revolutionary Performance',
    'cart.performanceText': 'Experience unmatched power and precision with our cutting-edge electric technology.',
    'cart.zeroMaintenance': 'Zero Maintenance',
    'cart.maintenanceText': 'No oil changes, spark plugs, or transmission maintenance required.',
    'cart.premiumSupport': 'Premium Support',
    'cart.supportText': 'Expert assembly, delivery, and ongoing customer support included.',
    
    // Footer
    'footer.ryft': 'Ryft',
    'footer.ryftDescription': 'Revolutionizing electric transportation with cutting-edge technology and sustainable design.',
    'footer.products': 'Products',
    'footer.specifications': 'Specifications',
    'footer.shop': 'Shop',
    'footer.support': 'Support',
    'footer.account': 'Account',
    'footer.company': 'Company',
    'footer.copyright': '© 2024 Ryft. All rights reserved.'
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Nosotros',
    'nav.contact': 'Contáctanos',
    'nav.products': 'Productos',
    'nav.support': 'Soporte',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.submit': 'Enviar',
    'common.close': 'Cerrar',
    
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.manage': 'Administra tu cuenta y preferencias',
    'profile.createAccount': 'Crear Cuenta',
    'profile.signIn': 'Iniciar Sesión',
    'profile.editProfile': 'Editar Perfil',
    'profile.logout': 'Cerrar Sesión',
    'profile.contactInfo': 'Información de Contacto',
    'profile.fullName': 'Nombre Completo',
    'profile.email': 'Correo Electrónico',
    'profile.phone': 'Número de Teléfono',
    'profile.address': 'Dirección',
    'profile.password': 'Contraseña',
    'profile.confirmPassword': 'Confirmar Contraseña',
    'profile.memberSince': 'Miembro desde',
    'profile.orders': 'Pedidos',
    'profile.totalSpent': 'Total Gastado',
    'profile.welcome': 'Bienvenido a Ryft',
    'profile.welcomeSubtitle': 'Crea tu cuenta o inicia sesión para comenzar',
    'profile.welcomeBack': '¡Bienvenido de vuelta! Por favor inicia sesión en tu cuenta.',
    'profile.joinRyft': '¡Únete a Ryft y comienza tu viaje eléctrico!',
    'profile.noOrders': 'Sin Pedidos Aún',
    'profile.noOrdersSubtitle': 'Comienza a comprar para ver tu historial de pedidos aquí.',
    'profile.startShopping': 'Comenzar a Comprar',
    'profile.wishlistEmpty': 'Tu Lista de Deseos Está Vacía',
    'profile.wishlistSubtitle': 'Comienza a agregar productos a tu lista de deseos para guardarlos para más tarde.',
    'profile.settingsComingSoon': 'Configuración Próximamente',
    'profile.settingsSubtitle': 'Las preferencias y configuraciones de cuenta estarán disponibles aquí.',
    'profile.securityComingSoon': 'Características de Seguridad Próximamente',
    'profile.securitySubtitle': 'La gestión de contraseñas y configuraciones de seguridad estarán disponibles aquí.',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.cancel': 'Cancelar',
    'profile.backToOptions': 'Volver a las opciones',
    'profile.enterFullName': 'Ingresa tu nombre completo',
    'profile.enterEmail': 'Ingresa tu correo electrónico',
    'profile.enterPhone': 'Ingresa tu número de teléfono',
    'profile.enterAddress': 'Ingresa tu dirección',
    'profile.createPassword': 'Crea una contraseña',
    'profile.newPassword': 'Ingresa nueva contraseña (déjalo en blanco para mantener la actual)',
    'profile.confirmNewPassword': 'Confirmar nueva contraseña',
    'profile.notSet': 'No establecido',
    'profile.maskedPassword': '••••••••',
    
    // Languages
    'languages.title': 'Elige Tu Idioma',
    'languages.subtitle': 'Selecciona tu idioma preferido para ver el sitio web de Ryft',
    'languages.apply': 'Aplicar Idioma',
    'languages.changed': '¡Idioma cambiado exitosamente!',
    'languages.reloading': 'Recargando página con nuevo idioma...',
    
    // Home Page
    'home.moveDifferent': 'Muévete Diferente. Monta el Cambio.',
    'home.explore': 'Explorar',
    'home.performanceLeads': 'Rendimiento que Lidera',
    'home.range75': 'Rango de 75 Millas',
    'home.rangeSubtitle': 'Ve más lejos con nuestra tecnología de batería de próxima generación.',
    'home.torque80': 'Par de 80Nm',
    'home.torqueSubtitle': 'Entrega de potencia instantánea con control suave.',
    'home.appControl': 'Control por App',
    'home.appSubtitle': 'Rastrea viajes, bloquea remotamente, monitorea el rendimiento.',
    'home.gallery': 'Galería',
    'home.ourMission': 'Nuestra Misión',
    'home.pioneeringFuture': 'Pioneros del Futuro',
    'home.missionText': 'Ryft está siendo pionero en el futuro del rendimiento eléctrico. Nuestra misión es entregar potencia, precisión y pureza sin compromisos — permitiendo que cada conductor desafíe el terreno, redefina la aventura y abrace el dominio eléctrico.',
    'home.power': 'Potencia',
    'home.powerSubtitle': 'Rendimiento eléctrico sin compromisos que supera la combustión tradicional',
    'home.precision': 'Precisión',
    'home.precisionSubtitle': 'Diseñado para control y manejo perfectos en cualquier condición',
    'home.purity': 'Pureza',
    'home.puritySubtitle': 'Tecnología limpia y sostenible que respeta nuestro planeta',
    'home.whyRyft': '¿Por qué \'Ryft\'?',
    'home.moreThanName': 'Más Que un Nombre',
    'home.philosophy': 'La Filosofía',
    'home.theRift': 'La Grieta',
    'home.riftText': 'La "grieta" entre el pasado de gasolina y el futuro electrificado. Donde la fuerza bruta se encuentra con la inteligencia. Donde el silencio habla de poder.',
    'home.theRevolution': 'La Revolución',
    'home.revolutionText': 'No solo estamos construyendo bicicletas eléctricas — estamos creando una revolución en cómo la gente piensa sobre el rendimiento, la sostenibilidad y el futuro del transporte.',
    'home.theMeaning': 'El Significado',
    'home.revolutionary': 'R - Revolucionario',
    'home.revolutionaryText': 'Liberándose de las limitaciones y restricciones tradicionales de la tecnología de combustión.',
    'home.youthful': 'Y - Juvenil',
    'home.youthfulText': 'Abrazando la innovación y mirando hacia el futuro con optimismo y energía.',
    'home.freedom': 'F - Libertad',
    'home.freedomText': 'La libertad de conducir en cualquier lugar, en cualquier momento, sin culpa ambiental o preocupación mecánica.',
    'home.technology': 'T - Tecnología',
    'home.technologyText': 'Tecnología eléctrica de vanguardia que empuja los límites de lo posible.',
    'home.whereSilence': 'Donde el silencio habla de poder.',
    'home.ryftPhilosophy': '— La Filosofía Ryft',
    'home.whatIsRyft': '¿Qué es Ryft?',
    'home.whatIsRyftText': 'Ryft no es solo una bicicleta eléctrica. Es un movimiento. Diseñada con precisión, construida con alma, y lista para redefinir la conducción eléctrica para una nueva generación.',
    'home.learnMore': 'Saber Más',
    'home.readyToRide': '¿Listo para Conducir?',
    'home.readyToRideText': 'Haz el pedido anticipado del Ryft One y únete al movimiento eléctrico.',
    'home.preorderNow': 'Hacer Pedido Anticipado Ahora',
    
    // About Page
    'about.title': 'Sobre Ryft',
    'about.subtitle': 'Estamos revolucionando el transporte eléctrico creando vehículos eléctricos de vanguardia que combinan tecnología innovadora, diseño sostenible y rendimiento excepcional.',
    'about.ourMission': 'Nuestra Misión',
    'about.missionText': 'Acelerar la transición del mundo al transporte sostenible haciendo vehículos eléctricos que no solo sean respetuosos con el medio ambiente, sino también emocionantes de conducir, hermosos de ver y accesibles para todos. Creemos que el futuro de la movilidad debe ser limpio, eficiente e inspirador.',
    'about.ourValues': 'Nuestros Valores',
    'about.innovation': 'Innovación',
    'about.innovationText': 'Empujando los límites de la tecnología de transporte eléctrico',
    'about.sustainability': 'Sostenibilidad',
    'about.sustainabilityText': 'Comprometidos a reducir la huella de carbono y proteger nuestro planeta',
    'about.quality': 'Calidad',
    'about.qualityText': 'Entregando productos excepcionales que superan las expectativas del cliente',
    'about.community': 'Comunidad',
    'about.communityText': 'Construyendo una comunidad global de entusiastas de vehículos eléctricos',
    'about.ourStory': 'Nuestra Historia',
    'about.storyText1': 'Fundada en 2025, Ryft comenzó como una visión audaz compartida por dos ambiciosos estudiantes de segundo año de secundaria que soñaban con revolucionar el transporte eléctrico.',
    'about.storyText2': 'Comenzamos en nuestros dormitorios y garajes, aprendiendo todo lo que pudimos sobre vehículos eléctricos, tecnología de baterías y diseño sostenible. Lo que comenzó como un proyecto escolar ha evolucionado hasta convertirse en una empresa real con la misión de hacer el transporte eléctrico accesible para todos.',
    'about.storyText3': 'A pesar de ser jóvenes empresarios, estamos determinados a demostrar que la edad es solo un número cuando se trata de innovación. Estamos construyendo el futuro de la movilidad mientras aún asistimos a la secundaria, mostrando que las grandes ideas pueden venir de cualquier lugar y de cualquier persona.',
    'about.fromHighSchool': 'De la Secundaria a la Innovación',
    'about.fromHighSchoolText': 'Nuestro viaje de estudiantes a empresarios',
    'about.meetOurTeam': 'Conoce Nuestro Equipo',
    'about.ceo': 'CEO',
    'about.cmo': 'CMO',
    'about.ceoBio': 'Liderando Ryft con una visión para revolucionar el transporte eléctrico y hacer la movilidad sostenible accesible para todos.',
    'about.cmoBio': 'Impulsando la estrategia de marketing de Ryft y el desarrollo de marca para conectar con entusiastas de vehículos eléctricos en todo el mundo.',
    'about.byTheNumbers': 'Por los Números',
    'about.vehiclesDelivered': 'Vehículos Entregados',
    'about.countriesServed': 'Países Atendidos',
    'about.teamMembers': 'Miembros del Equipo',
    'about.customerSatisfaction': 'Satisfacción del Cliente',
    
    // Contact Page
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Ponte en contacto con nuestro equipo. Estamos aquí para ayudarte a experimentar el futuro del transporte eléctrico.',
    'contact.howCanWeHelp': '¿Cómo Podemos Ayudarte?',
    'contact.callUs': 'Llámanos',
    'contact.callSubtitle': 'Habla directamente con nuestro equipo',
    'contact.emailUs': 'Envíanos un Email',
    'contact.emailSubtitle': 'Envíanos un mensaje detallado',
    'contact.liveChat': 'Chat en Vivo',
    'contact.chatSubtitle': 'Obtén ayuda instantánea en línea',
    'contact.sendMessage': 'Envíanos un Mensaje',
    'contact.name': 'Nombre',
    'contact.email': 'Correo Electrónico',
    'contact.phone': 'Teléfono',
    'contact.subject': 'Asunto',
    'contact.message': 'Mensaje',
    'contact.selectSubject': 'Selecciona un asunto',
    'contact.generalInquiry': 'Consulta General',
    'contact.salesQuestion': 'Pregunta de Ventas',
    'contact.technicalSupport': 'Soporte Técnico',
    'contact.testRideRequest': 'Solicitud de Prueba de Manejo',
    'contact.warrantyClaim': 'Reclamo de Garantía',
    'contact.partsService': 'Partes y Servicio',
    'contact.yourFullName': 'Tu nombre completo',
    'contact.emailPlaceholder': 'tu.correo@ejemplo.com',
    'contact.phonePlaceholder': '+1 (555) 123-4567',
    'contact.tellUsHow': 'Cuéntanos cómo podemos ayudarte...',
    'contact.sendMessageButton': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.thankYou': '¡Gracias! Tu mensaje ha sido enviado exitosamente.',
    'contact.somethingWentWrong': 'Algo salió mal. Por favor inténtalo de nuevo.',
    
    // Cart Page
    'cart.title': 'Tu Carrito',
    'cart.subtitle': 'artículo en tu carrito',
    'cart.subtitlePlural': 'artículos en tu carrito',
    'cart.emptyTitle': 'Tu carrito está vacío',
    'cart.emptySubtitle': '¿Listo para experimentar el futuro de la conducción eléctrica?',
    'cart.continueShopping': 'Continuar Comprando',
    'cart.orderSummary': 'Resumen del Pedido',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Envío',
    'cart.tax': 'Impuestos',
    'cart.total': 'Total',
    'cart.free': 'Gratis',
    'cart.warranty': 'Garantía Integral de 3 Años',
    'cart.freeShipping': 'Envío y Ensamblaje Gratis',
    'cart.securePayment': 'Procesamiento de Pago Seguro',
    'cart.proceedToCheckout': 'Proceder al Pago',
    'cart.whyChooseRyft': '¿Por Qué Elegir Ryft?',
    'cart.revolutionaryPerformance': 'Rendimiento Revolucionario',
    'cart.performanceText': 'Experimenta potencia y precisión inigualables con nuestra tecnología eléctrica de vanguardia.',
    'cart.zeroMaintenance': 'Cero Mantenimiento',
    'cart.maintenanceText': 'No se requieren cambios de aceite, bujías o mantenimiento de transmisión.',
    'cart.premiumSupport': 'Soporte Premium',
    'cart.supportText': 'Ensamblaje experto, entrega y soporte continuo al cliente incluidos.',
    
    // Footer
    'footer.ryft': 'Ryft',
    'footer.ryftDescription': 'Revolucionando el transporte eléctrico con tecnología de vanguardia y diseño sostenible.',
    'footer.products': 'Productos',
    'footer.specifications': 'Especificaciones',
    'footer.shop': 'Tienda',
    'footer.support': 'Soporte',
    'footer.account': 'Cuenta',
    'footer.company': 'Empresa',
    'footer.copyright': '© 2024 Ryft. Todos los derechos reservados.'
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.contact': 'Contactez-nous',
    'nav.products': 'Produits',
    'nav.support': 'Support',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.close': 'Fermer',
    
    // Profile
    'profile.title': 'Mon Profil',
    'profile.manage': 'Gérez votre compte et vos préférences',
    'profile.createAccount': 'Créer un Compte',
    'profile.signIn': 'Se Connecter',
    'profile.editProfile': 'Modifier le Profil',
    'profile.logout': 'Se Déconnecter',
    'profile.contactInfo': 'Informations de Contact',
    'profile.fullName': 'Nom Complet',
    'profile.email': 'E-mail',
    'profile.phone': 'Numéro de Téléphone',
    'profile.address': 'Adresse',
    'profile.password': 'Mot de Passe',
    'profile.confirmPassword': 'Confirmer le Mot de Passe',
    'profile.memberSince': 'Membre depuis',
    'profile.orders': 'Commandes',
    'profile.totalSpent': 'Total Dépensé',
    'profile.welcome': 'Bienvenue chez Ryft',
    'profile.welcomeSubtitle': 'Créez votre compte ou connectez-vous pour commencer',
    'profile.welcomeBack': 'Bon retour ! Veuillez vous connecter à votre compte.',
    'profile.joinRyft': 'Rejoignez Ryft et commencez votre voyage électrique !',
    'profile.noOrders': 'Aucune Commande Encore',
    'profile.noOrdersSubtitle': 'Commencez à faire des achats pour voir votre historique de commandes ici.',
    'profile.startShopping': 'Commencer à Acheter',
    'profile.wishlistEmpty': 'Votre Liste de Souhaits Est Vide',
    'profile.wishlistSubtitle': 'Commencez à ajouter des produits à votre liste de souhaits pour les sauvegarder pour plus tard.',
    'profile.settingsComingSoon': 'Paramètres Bientôt Disponibles',
    'profile.settingsSubtitle': 'Les préférences et paramètres du compte seront disponibles ici.',
    'profile.securityComingSoon': 'Fonctionnalités de Sécurité Bientôt Disponibles',
    'profile.securitySubtitle': 'La gestion des mots de passe et les paramètres de sécurité seront disponibles ici.',
    'profile.saveChanges': 'Sauvegarder les Modifications',
    'profile.cancel': 'Annuler',
    'profile.backToOptions': 'Retour aux options',
    'profile.enterFullName': 'Entrez votre nom complet',
    'profile.enterEmail': 'Entrez votre e-mail',
    'profile.enterPhone': 'Entrez votre numéro de téléphone',
    'profile.enterAddress': 'Entrez votre adresse',
    'profile.createPassword': 'Créez un mot de passe',
    'profile.newPassword': 'Entrez un nouveau mot de passe (laissez vide pour garder l\'actuel)',
    'profile.confirmNewPassword': 'Confirmer le nouveau mot de passe',
    'profile.notSet': 'Non défini',
    'profile.maskedPassword': '••••••••',
    
    // Languages
    'languages.title': 'Choisissez Votre Langue',
    'languages.subtitle': 'Sélectionnez votre langue préférée pour voir le site web Ryft',
    'languages.apply': 'Appliquer la Langue',
    'languages.changed': 'Langue changée avec succès !',
    'languages.reloading': 'Rechargement de la page avec la nouvelle langue...',
    
    // Home Page
    'home.moveDifferent': 'Bougez Différemment. Conduisez le Changement.',
    'home.explore': 'Explorer',
    'home.performanceLeads': 'Performance Qui Mène',
    'home.range75': 'Autonomie de 75 Miles',
    'home.rangeSubtitle': 'Allez plus loin avec notre technologie de batterie de nouvelle génération.',
    'home.torque80': 'Couple de 80Nm',
    'home.torqueSubtitle': 'Livraison de puissance instantanée avec contrôle fluide.',
    'home.appControl': 'Contrôle par App',
    'home.appSubtitle': 'Suivez les trajets, verrouillez à distance, surveillez les performances.',
    'home.gallery': 'Galerie',
    'home.ourMission': 'Notre Mission',
    'home.pioneeringFuture': 'Pionniers de l\'Avenir',
    'home.missionText': 'Ryft est pionnier de l\'avenir de la performance électrique. Notre mission est de fournir puissance, précision et pureté sans compromis — permettant à chaque conducteur de défier le terrain, redéfinir l\'aventure et embrasser la domination électrique.',
    'home.power': 'Puissance',
    'home.powerSubtitle': 'Performance électrique sans compromis qui dépasse la combustion traditionnelle',
    'home.precision': 'Précision',
    'home.precisionSubtitle': 'Conçu pour un contrôle et une manipulation parfaits dans toutes les conditions',
    'home.purity': 'Pureté',
    'home.puritySubtitle': 'Technologie propre et durable qui respecte notre planète',
    'home.whyRyft': 'Pourquoi \'Ryft\' ?',
    'home.moreThanName': 'Plus Qu\'un Nom',
    'home.philosophy': 'La Philosophie',
    'home.theRift': 'La Faille',
    'home.riftText': 'La "faille" entre le passé de l\'essence et l\'avenir électrifié. Où la force brute rencontre l\'intelligence. Où le silence parle de pouvoir.',
    'home.theRevolution': 'La Révolution',
    'home.revolutionText': 'Nous ne construisons pas seulement des vélos électriques — nous créons une révolution dans la façon dont les gens pensent à la performance, la durabilité et l\'avenir du transport.',
    'home.theMeaning': 'La Signification',
    'home.revolutionary': 'R - Révolutionnaire',
    'home.revolutionaryText': 'Se libérer des contraintes et limitations traditionnelles de la technologie de combustion.',
    'home.youthful': 'Y - Jeunesse',
    'home.youthfulText': 'Embrasser l\'innovation et regarder vers l\'avenir avec optimisme et énergie.',
    'home.freedom': 'F - Liberté',
    'home.freedomText': 'La liberté de conduire n\'importe où, n\'importe quand, sans culpabilité environnementale ou inquiétude mécanique.',
    'home.technology': 'T - Technologie',
    'home.technologyText': 'Technologie électrique de pointe qui repousse les limites du possible.',
    'home.whereSilence': 'Où le silence parle de pouvoir.',
    'home.ryftPhilosophy': '— La Philosophie Ryft',
    'home.whatIsRyft': 'Qu\'est-ce que Ryft ?',
    'home.whatIsRyftText': 'Ryft n\'est pas seulement un vélo électrique. C\'est un mouvement. Conçu avec précision, construit avec âme, et prêt à redéfinir la conduite électrique pour une nouvelle génération.',
    'home.learnMore': 'En Savoir Plus',
    'home.readyToRide': 'Prêt à Conduire ?',
    'home.readyToRideText': 'Précommandez le Ryft One et rejoignez le mouvement électrique.',
    'home.preorderNow': 'Précommander Maintenant',
    
    // About Page
    'about.title': 'À Propos de Ryft',
    'about.subtitle': 'Nous révolutionnons le transport électrique en créant des véhicules électriques de pointe qui combinent technologie innovante, design durable et performance exceptionnelle.',
    'about.ourMission': 'Notre Mission',
    'about.missionText': 'Accélérer la transition du monde vers le transport durable en créant des véhicules électriques qui ne sont pas seulement respectueux de l\'environnement, mais aussi passionnants à conduire, beaux à regarder et accessibles à tous. Nous croyons que l\'avenir de la mobilité doit être propre, efficace et inspirant.',
    'about.ourValues': 'Nos Valeurs',
    'about.innovation': 'Innovation',
    'about.innovationText': 'Repousser les limites de la technologie de transport électrique',
    'about.sustainability': 'Durabilité',
    'about.sustainabilityText': 'Engagés à réduire l\'empreinte carbone et protéger notre planète',
    'about.quality': 'Qualité',
    'about.qualityText': 'Fournir des produits exceptionnels qui dépassent les attentes des clients',
    'about.community': 'Communauté',
    'about.communityText': 'Construire une communauté mondiale d\'enthousiastes de véhicules électriques',
    'about.ourStory': 'Notre Histoire',
    'about.storyText1': 'Fondée en 2025, Ryft a commencé comme une vision audacieuse partagée par deux étudiants ambitieux de deuxième année du lycée qui rêvaient de révolutionner le transport électrique.',
    'about.storyText2': 'Nous avons commencé dans nos chambres et garages, apprenant tout ce que nous pouvions sur les véhicules électriques, la technologie des batteries et le design durable. Ce qui a commencé comme un projet scolaire a évolué vers une vraie entreprise avec la mission de rendre le transport électrique accessible à tous.',
    'about.storyText3': 'Malgré être de jeunes entrepreneurs, nous sommes déterminés à prouver que l\'âge n\'est qu\'un nombre quand il s\'agit d\'innovation. Nous construisons l\'avenir de la mobilité tout en fréquentant encore le lycée, montrant que les grandes idées peuvent venir de n\'importe où et de n\'importe qui.',
    'about.fromHighSchool': 'Du Lycée à l\'Innovation',
    'about.fromHighSchoolText': 'Notre voyage d\'étudiants à entrepreneurs',
    'about.meetOurTeam': 'Rencontrez Notre Équipe',
    'about.ceo': 'PDG',
    'about.cmo': 'DMM',
    'about.ceoBio': 'Diriger Ryft avec une vision de révolutionner le transport électrique et rendre la mobilité durable accessible à tous.',
    'about.cmoBio': 'Conduire la stratégie marketing de Ryft et le développement de marque pour connecter avec les enthousiastes de véhicules électriques dans le monde entier.',
    'about.byTheNumbers': 'Par les Chiffres',
    'about.vehiclesDelivered': 'Véhicules Livrés',
    'about.countriesServed': 'Pays Servis',
    'about.teamMembers': 'Membres de l\'Équipe',
    'about.customerSatisfaction': 'Satisfaction Client',
    
    // Contact Page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Contactez notre équipe. Nous sommes là pour vous aider à expérimenter l\'avenir du transport électrique.',
    'contact.howCanWeHelp': 'Comment Pouvons-nous Vous Aider ?',
    'contact.callUs': 'Appelez-nous',
    'contact.callSubtitle': 'Parlez directement avec notre équipe',
    'contact.emailUs': 'Envoyez-nous un E-mail',
    'contact.emailSubtitle': 'Envoyez-nous un message détaillé',
    'contact.liveChat': 'Chat en Direct',
    'contact.chatSubtitle': 'Obtenez de l\'aide instantanée en ligne',
    'contact.sendMessage': 'Envoyez-nous un Message',
    'contact.name': 'Nom',
    'contact.email': 'E-mail',
    'contact.phone': 'Téléphone',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.selectSubject': 'Sélectionnez un sujet',
    'contact.generalInquiry': 'Demande Générale',
    'contact.salesQuestion': 'Question de Vente',
    'contact.technicalSupport': 'Support Technique',
    'contact.testRideRequest': 'Demande d\'Essai de Conduite',
    'contact.warrantyClaim': 'Réclamation de Garantie',
    'contact.partsService': 'Pièces et Service',
    'contact.yourFullName': 'Votre nom complet',
    'contact.emailPlaceholder': 'votre.email@exemple.com',
    'contact.phonePlaceholder': '+1 (555) 123-4567',
    'contact.tellUsHow': 'Dites-nous comment nous pouvons vous aider...',
    'contact.sendMessageButton': 'Envoyer le Message',
    'contact.sending': 'Envoi...',
    'contact.thankYou': 'Merci ! Votre message a été envoyé avec succès.',
    'contact.somethingWentWrong': 'Quelque chose s\'est mal passé. Veuillez réessayer.',
    
    // Cart Page
    'cart.title': 'Votre Panier',
    'cart.subtitle': 'article dans votre panier',
    'cart.subtitlePlural': 'articles dans votre panier',
    'cart.emptyTitle': 'Votre panier est vide',
    'cart.emptySubtitle': 'Prêt à expérimenter l\'avenir de la conduite électrique ?',
    'cart.continueShopping': 'Continuer les Achats',
    'cart.orderSummary': 'Résumé de la Commande',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Expédition',
    'cart.tax': 'Taxe',
    'cart.total': 'Total',
    'cart.free': 'Gratuit',
    'cart.warranty': 'Garantie Complète de 3 Ans',
    'cart.freeShipping': 'Expédition et Assemblage Gratuits',
    'cart.securePayment': 'Traitement de Paiement Sécurisé',
    'cart.proceedToCheckout': 'Procéder au Paiement',
    'cart.whyChooseRyft': 'Pourquoi Choisir Ryft ?',
    'cart.revolutionaryPerformance': 'Performance Révolutionnaire',
    'cart.performanceText': 'Expérimentez puissance et précision inégalées avec notre technologie électrique de pointe.',
    'cart.zeroMaintenance': 'Zéro Maintenance',
    'cart.maintenanceText': 'Aucun changement d\'huile, bougies ou maintenance de transmission requis.',
    'cart.premiumSupport': 'Support Premium',
    'cart.supportText': 'Assemblage expert, livraison et support client continu inclus.',
    
    // Footer
    'footer.ryft': 'Ryft',
    'footer.ryftDescription': 'Révolutionner le transport électrique avec une technologie de pointe et un design durable.',
    'footer.products': 'Produits',
    'footer.specifications': 'Spécifications',
    'footer.shop': 'Boutique',
    'footer.support': 'Support',
    'footer.account': 'Compte',
    'footer.company': 'Entreprise',
    'footer.copyright': '© 2024 Ryft. Tous droits réservés.'
  }
};

// Add more languages as needed...

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('ryft-language');
    if (savedLanguage && translations[savedLanguage as keyof typeof translations]) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (languageCode: string) => {
    if (translations[languageCode as keyof typeof translations]) {
      setCurrentLanguage(languageCode);
      localStorage.setItem('ryft-language', languageCode);
      
      // Show success message
      const successMessage = translations[languageCode as keyof typeof translations]['languages.changed'] || 'Language changed successfully!';
      
      // Create a toast notification
      const toast = document.createElement('div');
      toast.className = 'fixed top-4 right-4 bg-green-500 text-white px-6 py-3 rounded-lg shadow-lg z-50 transform transition-all duration-300 translate-x-full';
      toast.textContent = successMessage;
      document.body.appendChild(toast);
      
      // Animate in
      setTimeout(() => {
        toast.classList.remove('translate-x-full');
      }, 100);
      
      // Animate out and remove
      setTimeout(() => {
        toast.classList.add('translate-x-full');
        setTimeout(() => {
          document.body.removeChild(toast);
        }, 300);
      }, 3000);
      
      // Reload the page after a short delay to apply the new language
      setTimeout(() => {
        window.location.reload();
      }, 1500);
    }
  };

  const t = (key: string): string => {
    const langTranslations = translations[currentLanguage as keyof typeof translations];
    if (langTranslations && langTranslations[key as keyof typeof langTranslations]) {
      return langTranslations[key as keyof typeof langTranslations];
    }
    // Fallback to English if translation not found
    return translations.en[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
